In [20]:
import requests
from bs4 import BeautifulSoup

In [178]:
def extract(page):
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15'}
    url = f'https://uk.indeed.com/jobs?q=data%20science&l=nationwide&start={page}'
    r = requests.get(url, headers)
    soup = BeautifulSoup(r.content, 'html.parser')
    return soup

In [196]:
def transform(soup):
    divs = soup.find_all('a', attrs={'class':'tapItem'})
    for item in divs:
        title = item.find('div', attrs={'class':'heading4'}).text.strip()
        company = item.find('span', attrs={'class':'companyName'}).text.strip()
        summary = item.find('div', attrs={'class':'job-snippet'}).text.strip()
        try:
            salary = item.find('div', attrs={'class':'metadata salary-snippet-container'}).text.strip()
        except:
            salary=''
            
        job = {
            'title':title,
            'company':company,
            'summary':summary,
            'salary':salary
        }
        joblist.append(job)
    return
joblist=[]

In [201]:
for page in range(0,50,10):
    page_data = extract(page)
    transform(page_data)

In [202]:
df = pd.DataFrame(joblist)

In [206]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df)

,title,company,summary,salary
0,The Information Lab - Data Consulting Analyst,Metrica Recruitment,"For the first year you will be paid £30K, quic...","£30,000 a year"
1,newHead of R&D Data and Strategic Projects,The Body Shop International Limited,Delivery: As an expert in R&D data and tools y...,
2,newLab Clinical Data Analyst,IQVIA,Record all evidence of the data transmission p...,
3,Bioinformatician,"Centre for Environment, Fisheries and Aquacult...","Analysis of HTS-derived data (amplicon based, ...","£29,267 - £32,766 a year"
4,newBusiness Intelligence and Data Lab Manager,Trafford Council,A passion for data and aptitude in supporting ...,"£40,876 - £42,821 a year"
5,newMachine Learning for Radiology Scientist,The Royal Marsden NHS Foundation Trust,These readouts will be used by clinicians mana...,"£43,712 - £49,325 a year"
6,newData Geoscientist,CGG,You will also have experience of working with ...,
7,Scientific Data Researcher,Givaudan,Establish links and partner with internal grou...,
8,Data Analyst role within Flow Cytometry lab,IQVIA,With a relentless focus on quality and innovat...,
9,newPostdoctoral Research Assistant in machine ...,University of Oxford,The successful candidate will be responsible f...,"£32,817 - £40,322 a year"
10,Machine Learning Scientist,Deep Planet,The post holder will be developing ML algorith...,
11,"Marketing Data Analyst, Media Labs",Google,"Maintenance of data such as cleaning, structur...",
12,Early Careers - Graduate Research Executive - ...,Ipsos,"A background or degree in science, medicine or...","£25,000 a year"
13,Quantitative Ecologist SD20/272,Animal and Plant Health Agency,Experience of interpreting scientific data and...,"£29,179 - £32,160 a year"
14,newPostdoctoral Research Scientist — Agricultu...,Rothamsted Research,Successful candidates will possess a PhD in ag...,"£31,350 a year"
15,The Information Lab - Data Consulting Analyst,Metrica Recruitment,"For the first year you will be paid £30K, quic...","£30,000 a year"
16,newHead of R&D Data and Strategic Projects,The Body Shop International Limited,Delivery: As an expert in R&D data and tools y...,
17,Biochemistry Analyst,Marketplace Technical,To adhere to record and data integrity require...,
18,newLab Clinical Data Analyst,IQVIA,Record all evidence of the data transmission p...,
19,Bioinformatician,"Centre for Environment, Fisheries and Aquacult...","Analysis of HTS-derived data (amplicon based, ...","£29,267 - £32,766 a year"
20,newBusiness Intelligence and Data Lab Manager,Trafford Council,A passion for data and aptitude in supporting ...,"£40,876 - £42,821 a year"
21,newMachine Learning for Radiology Scientist,The Royal Marsden NHS Foundation Trust,These readouts will be used by clinicians mana...,"£43,712 - £49,325 a year"
22,newData Geoscientist,CGG,You will also have experience of working with ...,
23,Scientific Data Researcher,Givaudan,Establish links and partner with internal grou...,
24,Data Analyst role within Flow Cytometry lab,IQVIA,With a relentless focus on quality and innovat...,
25,newPostdoctoral Research Assistant in machine ...,University of Oxford,The successful candidate will be responsible f...,"£32,817 - £40,322 a year"
26,Machine Learning Scientist,Deep Planet,The post holder will be developing ML algorith...,
27,"Marketing Data Analyst, Media Labs",Google,"Maintenance of data such as cleaning, structur...",
28,Early Careers - Graduate Research Executive - ...,Ipsos,"A background or degree in science, medicine or...","£25,000 a year"
29,Quantitative Ecologist SD20/272,Animal and Plant Health Agency,Experience of interpreting scientific data and...,"£29,179 - £32,160 a year"
30,Quantitative geneticist / Bioinformatician - A...,XELECT,Previous demonstrable experience of analysing ...,"£32,000 - £42,000 a year"
31,"Marketing Data Analyst, Media Labs",Google,"Maintenance of data such as cleaning, structur...",
32,newData Geoscientist,CGG,You will also have experience of working with ...,
33,"Marketing Science, Analytics Sandwich Placement",Mindshare,"Reporting to the Director of Analytics, the ma...",
34,newLab Clinical Data Analyst,IQVIA,Record all evidence of the data transmission p...,
35,The Information Lab - Data Consulting Analyst,Metrica Recruitment,"For the first year you will be paid £30K, quic...","£30,000 a year"
36,"Manager, Clinical Science Analytics & Insights...",Clinical Solutions,Experience with electronic data capture system...,
37,Data Analyst role within Flow Cytometry lab,IQVIA,With a relentless focus on quality and innovat...,
38,newMachine Learning for Radiology Scientist,The Royal Marsden NHS Foundation Trust,These readouts will be used by clinicians mana...,"£43,712 - £49,325 a year"
39,Machine Learning Scientist,Deep Planet,The post holder will be developing ML algorith...,
40,Scientist (Biostatistician),Genomics plc,"As a Precision Health Scientist, you will inte...",
41,Early Careers - Graduate Research Executive - ...,Ipsos,"A background or degree in science, medicine or...","£25,000 a year"
42,Bioinformatician (Protein Data Bank in Europe ...,European Molecular Biology Laboratory,To design and develop a process for data integ...,
43,Machine Learning Scientist Intern,Zebra Technologies,Internship applicants will generally study tow...,
44,Cancer Bioinformatician,Cambridge Cancer Genomics,Maintaining core bioinformatics infrastructure...,
45,Cancer Bioinformatician,Cambridge Cancer Genomics,Maintaining core bioinformatics infrastructure...,
46,"Senior Scientist, Clinical Science Analytics &...",Clinical Solutions,We combine deep science with deep data from ad...,
47,newQuantitative Research - Credit Securities a...,"JPMorgan Chase Bank, N.A.",The Credit Securities and Financing QR team is...,
48,"Machine Learning Scientist, Deep Learning",Evi Technologies Limited,"Participate in the design, development, evalua...",
49,newQuantitative Research - Rates Hybrids - Ass...,"JPMorgan Chase Bank, N.A.",Relevant education would be in the area of Fin...,
50,Bioinformatician,University of Cambridge,Mass-spetctrometry data analysis - processing ...,"£36,914 - £49,553 a year"
51,newPostdoctoral Research Assistant in machine ...,University of Oxford,The successful candidate will be responsible f...,"£32,817 - £40,322 a year"
52,Quantitative Ecologist SD20/272,Animal and Plant Health Agency,Experience of interpreting scientific data and...,"£29,179 - £32,160 a year"
53,Machine Learning Scientist,GreySpark Partners,Supervising the data acquisition process if mo...,
54,QC Analyst - Molecular Biology,SGS,Perform all laboratory work and data analysis ...,
55,Research Analyst,Cogentia Healthcare Consulting,Analysing qualitative and quantitative data.\n...,
56,Geoscience Data Specialist / Data Engineer,CGG,Familiarity with creating data pipelines to bo...,
57,Bioinformatician / Computational Biologist,University of Glasgow,E15 Extensive and established international re...,"£35,845 - £40,322 a year"
58,newHead of R&D Data and Strategic Projects,The Body Shop International Limited,Delivery: As an expert in R&D data and tools y...,
59,newQuantitative Research - Commodities - Vice ...,"JPMorgan Chase Bank, N.A.",We are seeking a person to join a team within ...,
60,Data Engineer - Data Lab,M&G plc,Experience in a data science role using data s...,
61,Bioinformatician - Scientist,BioClavis,Must be familiar with analyzing and manipulati...,
62,Bioinformatician,"Centre for Environment, Fisheries and Aquacult...","Analysis of HTS-derived data (amplicon based, ...","£29,267 - £32,766 a year"
63,Bioinformatician,The University of Manchester,"In recent years, whole genome sequencing data ...","£32,816 - £40,322 a year"
64,Quantum Algorithms and Machine Learning Scientist,Cambridge Quantum Computing,The quantum computers available today have pro...,
65,newSenior Bioinformatician - Immune Mediated D...,Wellcome Sanger Institute,The work includes managing various data collec...,"£37,865 - £45,359 a year"
66,Research Assistant in Physics-Aware Data Assim...,Imperial College London,Develop physics-aware data assimilation for un...,"£36,045 - £39,183 a year"
67,"Manager, Clinical Science Analytics & Insight",Precision Medicine Group,Experience with electronic data capture system...,
68,newBusiness Intelligence and Data Lab Manager,Trafford Council,A passion for data and aptitude in supporting ...,"£40,876 - £42,821 a year"
69,Scientific Data Engineer,Exscientia,Create dependable data ingest services using P...,
70,Scientific Data Researcher,Givaudan,Establish links and partner with internal grou...,
71,newAnalytical Scientist - Statistical and Clin...,The Institute of Cancer Research,You will perform routine statistical analysis ...,"£32,000 - £44,400 a year"
72,Machine Learning Research Scientist,nPlan,We are a data driven company heavily focused a...,
73,Machine Learning Scientist - RCYTHQ0040,Cyted Ltd,Integrating with cloud APIs and data services....,
74,Machine Learning Scientist- Alexa,Evi Technologies Limited,"Strong knowledge of data structures, algorithm...",
75,Machine Learning Scientist,GreySpark Partners,Supervising the data acquisition process if mo...,
76,Scientific Data Engineer,Exscientia,Create dependable data ingest services using P...,
77,Statistics Teaching Fellow,University of Edinburgh,"Full-time, 35 hours per week.\nFixed Term - av...",
78,Quantitative ESG Researcher,Richmond Global Sciences (RGS),"Ability to interpret data, theorize, and make ...",
79,newAnalytical Scientist - Statistical and Clin...,The Institute of Cancer Research,You will perform routine statistical analysis ...,"£32,000 - £44,400 a year"
80,Quantitative Researcher in Natural Language Pr...,G-Research,This is a pure research role that would suit t...,
81,newQuantitative Research - Credit Securities a...,"JPMorgan Chase Bank, N.A.",The Credit Securities and Financing QR team is...,
82,Bioinformatician,The University of Manchester,"In recent years, whole genome sequencing data ...","£32,816 - £40,322 a year"
83,Scientist - Process Analytics,Lonza,This is a lab based position that requires equ...,
84,Bioinformatician - Scientist,BioClavis,Must be familiar with analyzing and manipulati...,
85,AI Scientist - Machine Learning,PGSM Consulting,"Analyze data to discover patterns, find opport...",
86,newQuantitative Research - Commodities - Vice ...,"JPMorgan Chase Bank, N.A.",We are seeking a person to join a team within ...,
87,Statistical Science Associate Director - Early...,AstraZeneca,"Extensive experience of Development, programme...",
88,Market Access Research Scientist,PHMR,PhD in life sciences or MSc/BSc with 2 years o...,
89,Laboratory Database Manager,University of Oxford,The Laboratory Database Manager is to oversee ...,"£29,176 - £34,804 a year"
90,Statistical Scientist (m/w/d),IQVIA,Provide expert input into data management deli...,
91,Machine Learning Scientist - RCYTHQ0040,Cyted Ltd,Integrating with cloud APIs and data services....,
92,Quantitative Researcher (New Ventures),G-Research,"We pair this expertise with machine learning, ...",
93,Machine Learning Scientist,Exogene Limited,We generate the training data in-house at our ...,
94,Quant Analyst,Maven,"Exposure to real-world data exploration, dimen...",
95,Computational Biologist / Bioinformatician,Oxford Nanopore Technologies,You will also interact with other data analyst...,
96,Geoscience Data Consultant,Arcadis,Loading and manipulating and analysing AGS dat...,
97,newAssociate Principal Scientist in Computatio...,MSD,Demonstrated expertise in applying Machine Lea...,
98,Analytical Chemist - Data Verification,Rowland Talent Solutions,"Duties vary and will include, data verificatio...",
99,newDatabase Coordinator,Apollo Scientific,= Maintainingchemical database content ensurin...,"£18,000 - £20,000 a year"
100,Applied Scientist in Machine Learning for Simu...,Evi Technologies Limited,Experience in python’s machine learning and da...,
101,Business Science Manager - Systems Intelligence,MediaCom,Managers are key members of the Business Scien...,
102,Post-Doctoral Research Associate - Data Analysis,Diamond Light Source,You will hold a first degree in science / math...,"£33,963 - £39,955 a year"
103,Data Engineer - Data Lab,M&G plc,Experience in a data science role using data s...,
104,Quantitative Analyst - Execution Research,Smartodds,"Inside the quant team, you will be part of the...",