In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
def extract(page):
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15'}
    url = f'https://uk.indeed.com/jobs?q=data%20science&l=nationwide&start={page}'
    r = requests.get(url, headers)
    soup = BeautifulSoup(r.content, 'html.parser')
    return soup

In [3]:
def transform(soup):
    divs = soup.find_all('a', attrs={'class':'tapItem'})
    for item in divs:
        title = item.find('div', attrs={'class':'heading4'}).text.strip()
        company = item.find('span', attrs={'class':'companyName'}).text.strip()
        summary = item.find('div', attrs={'class':'job-snippet'}).text.strip()
        try:
            salary = item.find('div', attrs={'class':'metadata salary-snippet-container'}).text.strip()
        except:
            salary=''
            
        job = {
            'title':title,
            'company':company,
            'summary':summary,
            'salary':salary
        }
        joblist.append(job)
    return
joblist=[]

In [4]:
for page in range(0,50,10):
    page_data = extract(page)
    transform(page_data)

In [7]:
df = pd.DataFrame(joblist)

In [8]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df)

,title,company,summary,salary
0,Sales Excellence & Data Analyst,Minerva Research Labs / Gold Collagen,Recommend methods and ways to obtain and analy...,"£20,000 - £30,000 a year"
1,newApplied Machine Learning Scientist,ASB Research,Proven curiosity and passion around data inves...,"£34,264 - £93,893 a year"
2,Environmental Data Analyst,AlliedCrowds,"Degree in biology, environmental sciences, eco...","£36,000 a year"
3,The Information Lab - Data Consulting Analyst,Metrica Recruitment,"For the first year you will be paid £30K, quic...","£30,000 a year"
4,newMachine Learning Research Scientist,nPlan,We are a data driven company heavily focused a...,
5,newBioinformatician,Public Sector Resourcing,"Liaising with reporting, data analytics and wi...",
6,"Marketing Data Analyst, Media Labs",Google,"Maintenance of data such as cleaning, structur...",
7,"Marketing Science, Analytics Sandwich Placement",Mindshare,"Reporting to the Director of Analytics, the ma...",
8,Machine Learning Scientist - 100% Remote,Cazana,"Using big data and predictive analytics, Cazan...",
9,Geoscience Data Specialist,CGG,Familiarity with creating data pipelines to bo...,
10,Data Services Associate,AIR,"A degree in science, engineering or mathematic...",
11,Quantitative Research Analyst – Full Time (EMEA),CITADEL ENTERPRISE EUROPE LIMITED,Use unconventional data sources to drive innov...,
12,Bioinformatician (Algorithmic Development),Warman O'Brien,Strong experience of Oncology and multi-omic s...,"£60,000 a year"
13,"newComputational Biologist, Bioinformatician, ...",Corriculo,O Genomics including whole genome DNA sequenci...,£400 a day
14,Scientific Data Researcher,Givaudan,Establish links and partner with internal grou...,
15,Machine Learning Scientist,Monzo,Explore. We use BigQuery and Jupyter Notebooks...,
16,Bioinformatician (Algorithmic Development),Warman O'Brien,Strong experience of Oncology and multi-omic s...,"£60,000 a year"
17,newProgramme Coordinator (Environmental Future...,University of Exeter,We are seeking an experienced applicant to pro...,"£27,924 - £31,406 a year"
18,Quantitative Analyst,NatWest Markets,Testing implementations and back testing the e...,
19,Quantitative Researcher – PhD – Intern,Citadel Securities,Use unconventional data sources to drive innov...,
20,Bioinformatician – Human Genomics,Shift F5 Ltd,Top Python skills (Bio tool kit & various Data...,"£65,000 a year"
21,Senior Data Analyst,Getsafe GmbH,You are responsible for our data refinement pi...,
22,"Manager, Clinical Science Analytics & Insight",Precision Medicine Group,Experience with electronic data capture system...,
23,Research Associate (Meteorological / Climate d...,AIR,Verisk (Nasdaq: VRSK) provides data and insigh...,
24,newMolecular biologist/Bioinformatician (SD21/...,Animal and Plant Health Agency,Available to 30 June 2022 - with possibility o...,"£32,557 - £35,888 a year"
25,newMachine Learning Scientist,AIG,Build and refine Machine Learning algorithms t...,
26,newNHS Test and Trace - Principle Bioinformati...,Department of Health and Social Care,Experience communicating science to senior sta...,"£49,529 - £62,286 a year"
27,"newComputational Biologist, Bioinformatician, ...",Corriculo,O Genomics including whole genome DNA sequenci...,£400 a day
28,Machine Learning Scientist,Exogene Limited,We generate the training data in-house at our ...,
29,newInnovation Manager (Environmental Futures &...,University of Exeter,"Responsibility for business development, out-r...","£44,706 - £51,799 a year"
30,The Information Lab - Data Consulting Analyst,Metrica Recruitment,"For the first year you will be paid £30K, quic...","£30,000 a year"
31,Senior Data Analyst,Getsafe GmbH,You are responsible for our data refinement pi...,
32,"Manager, Clinical Science Analytics & Insight",Precision Medicine Group,Experience with electronic data capture system...,
33,Research Associate (Meteorological / Climate d...,AIR,Verisk (Nasdaq: VRSK) provides data and insigh...,
34,newMolecular biologist/Bioinformatician (SD21/...,Animal and Plant Health Agency,Available to 30 June 2022 - with possibility o...,"£32,557 - £35,888 a year"
35,newMachine Learning Scientist,AIG,Build and refine Machine Learning algorithms t...,
36,newNHS Test and Trace - Principle Bioinformati...,Department of Health and Social Care,Experience communicating science to senior sta...,"£49,529 - £62,286 a year"
37,Machine Learning Scientist,Exogene Limited,We generate the training data in-house at our ...,
38,newInnovation Manager (Environmental Futures &...,University of Exeter,"Responsibility for business development, out-r...","£44,706 - £51,799 a year"
39,Research Scientist - Machine Learning and Caus...,causaLens,PhD in a quantitative field (machine learning ...,
40,newResearch Scientist in Statistical Modelling,Sartorius,Developing innovative data analytics and stati...,
41,Research Scientist Manager — Statistical Learn...,Facebook,PhD and publications in a quantitative field s...,
42,Lead Cybersecurity Researcher (Cybersecurity S...,HSBC,You should have a background in computer scien...,
43,newQualitative Market Research Executive,Morgan Spencer,YOU WILL HAVE A DERGEE OR A LEVEL IN MATHEMATI...,"£26,000 a year"
44,Quantitative Biologist,XAI.bio,Masters or PhD in quantitative biology or syst...,"£40,000 - £50,000 a year"
45,Quantitative Researcher (New Ventures),G-Research,"We pair this expertise with machine learning, ...",
46,"Full Time Opportunities, Cambridge Residency: ...",Microsoft,Familiarity with techniques for ensuring data ...,
47,Bioinformatician - Gene Expression Team,European Molecular Biology Laboratory,"You will be involved in data production, writi...",
48,Quantitative Research - Rates Hybrids - Analys...,"JPMorgan Chase Bank, N.A.",Relevant education would be in the area of Fin...,
49,Research Analyst,Cogentia Healthcare Consulting,Analysing qualitative and quantitative data.\n...,
50,Pharmaceutical Laboratory Analyst,Northumbria Pharma,Ability to analyse and critically assess data ...,
51,Scientific Officer: ELIXIR Human Genomics and ...,European Molecular Biology Laboratory,ELIXIR unites Europe’s leading life science or...,
52,newAssociate Bioinformatician,Marketplace Technical,Experience in data manipulation and analysis o...,
53,Research Scientist — Statistics and Privacy,Facebook,Solid experience of post-PhD work in data scie...,
54,Quantitative Analyst - Execution Research,Smartodds,"Inside the quant team, you will be part of the...",
55,Quantitative Research - Credit Securities and ...,"JPMorgan Chase Bank, N.A.",The Credit Securities and Financing QR team is...,
56,21N/RPBI NGS Bioinformatician,Randox Laboratories,Employer Information…,
57,Associate Bioinformatician,QuantuMDx Group Ltd,Experience in data manipulation and analysis o...,
58,Quantitative Research Analyst – Intern (EMEA),CITADEL ENTERPRISE EUROPE LIMITED,Use unconventional data sources to drive innov...,
59,Machine Learning/Computer Vision Scientist (Ho...,re&m,FMachine Learning Engineers/Computer Vision Sc...,"£35,000 - £40,000 a year"
60,Data Engineer - Data Lab,M&G plc,Experience in a data science role using data s...,
61,Statistical Scientist - Real World Evidence,Icon plc,A as Statistical Scientist you are responsible...,
62,Lab Clinical Data Analyst,IQVIA,Record all evidence of the data transmission p...,
63,"Research Scientist, Natural Language Processin...",Cambridge Quantum Computing,Cambridge Quantum (CQ) is seeking to hire a fu...,
64,newBioinformatician in Genome Stability,University of Oxford,The aim of this role is to develop mathematica...,"£32,817 - £33,797 a year"
65,Chair in Statistical Science,University of Bristol,To lead internationally outstanding research i...,
66,newAssociate Bioinformatician,Marketplace Technical,Experience in data manipulation and analysis o...,
67,Research Associate (Genetic Bioinformatician),King's College London,"Knowledge of bioinformatics analysis methods, ...","£38,304 a year"
68,"Graduate Research Analyst, Aromatics & Fibers",IHS Markit,Maintain capacity and supply and demand data s...,
69,Genomic Applications Bioinformatician,Oxford Nanopore Technologies,"In addition, you'll have practical experience ...",